import '../recipes.infra.just'

# Default recipe - show available commands
help:
  @just --list

# Initialize Terraform (api-gateway stack)
[group('init')]
setup env +args="":
  @echo 'Creating tfbackend for {{BOLD + RED}}{{ env }}{{NORMAL}} environment'
  cp .config.tfbackend.example .config.local.tfbackend
  sed -i.bak "s|<terraform.state.bucket>|$TF_STATE_BUCKET|" .config.local.tfbackend
  sed -i.bak "s|<aws.region>|$AWS_REGION|" .config.local.tfbackend
  rm -f .config.local.tfbackend.bak

# Initialize Terraform (api-gateway stack)
[group('init')]
init env="dev" +args="": (clean) (setup env)
  @echo 'Initalizing for {{BOLD + RED}}{{ env }}{{NORMAL}} environment'
  terraform init --reconfigure --backend-config=.config.local.tfbackend {{args}}

# Clean up
[group('init')]
clean:
  @echo "Cleaning up..."
  rm -f .config.local.tfbackend
  rm -rf .terraform
