rules:
  unpinned-uses:
    config:
      policies:
        "actions/*": ref-pin
        "astral-sh/setup-uv": ref-pin
        "aws-actions/*": ref-pin
        "hashicorp/*": ref-pin
        "*": hash-pin

  cache-poisoning:
    disable: false
