---
branches:
  - main
tagFormat: "infra-global-v${version}"
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - {scope: infra-global, breaking: true, release: major}
        - {scope: infra-global, type: feat, release: minor}
        - {scope: infra-global, type: fix, release: patch}
        - {scope: infra-global, type: perf, release: patch}
        - {scope: infra-global, type: refactor, release: patch}
        - {breaking: true, release: false}
        - {type: feat, release: false}
        - {type: fix, release: false}
        - {type: perf, release: false}
        - {type: refactor, release: false}
        - {type: chore, release: false}
        - {type: docs, release: false}
        - {type: style, release: false}
        - {type: test, release: false}
        - {type: build, release: false}
        - {type: ci, release: false}
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
