import '../infra.recipes.just'

# Default recipe - show available commands
help:
  just --list

# Initialize Terraform (global stack)
[group('init')]
init env +args="":
  terraform init --reconfigure --backend-config=.config.{{env}}.tfbackend {{args}}

# Clean up
[group('init')]
clean:
  rm -rf .terraform
  rm -rf .terraform.lock.hcl

# Force lambda deployment
[group('deploy')]
deploy-lambda function bucket key:
  aws lambda update-function-code \
    --function-name {{ function }} \
    --s3-bucket {{ bucket }} \
    --s3-key {{ key }}
