lambda_function_name := "cbtc-media-day-dev-authorizer"

import '../recipes.services.just'

# Service-local Terraform stack
[group('infra')]
mod infra 'infra'

# Default recipe - show available commands
help:
    @just --list
