# Default recipe - show available commands
help:
  @just --list

# Clean up
[group('init')]
clean:
  @echo "Cleaning up..."
  rm -rf .terraform
  rm -rf .terraform.lock.hcl
  rm -rf terraform.tfstate
  rm -rf terraform.tfstate.backup

# Initialize Terraform (global stack)
[group('init')]
init +args="":
  terraform init

# Plan Terraform changes
[group('apply')]
plan env="dev" +args="":
  terraform plan --var="environment={{ env }}" {{ args }}

# Apply Terraform changes
[group('apply')]
apply env="dev" +args="":
  terraform apply --var="environment={{ env }}" {{ args }}
