import '../infra.recipes.just'

# Default recipe - show available commands
help:
  @just --list

# Initialize Terraform (global stack)
[group('init')]
init env +args="":
  terraform init --backend-config=.config.{{env}}.tfbackend {{args}}

# Clean up
[group('init')]
clean:
  @echo "Cleaning up..."
  rm -rf .terraform
  rm -rf .terraform.lock.hcl
  rm -rf terraform.tfstate
  rm -rf terraform.tfstate.backup
